### ISSUE TITLE
compose 사용시 manage.py를 찾지 못하는 문제

### ISSUE THREAD

**Issue by hyungjunk** [raccoonyy/django-sample-for-docker-compose#2]
<실행순서>
git clone https://github.com/raccoonyy/django-sample-for-docker-compose.git
cd django-sample-for-docker-compose/
docker-compose up

<결과>
python: can't open file 'manage.py': [Errno 2] No such file or directory

라고 출력됩니다.

**Comment by raccoonyy** [comment]
지난 커밋에서 `docker-compose.yml` 파일을 수정하면서 실수로 volume 설정까지 지웠네요. https://github.com/raccoonyy/django-sample-for-docker-compose/commit/cba1c238b0dc8c80bd5a130b2a217b5c3469a10f 에서 수정하였습니다.

버그를 알려주셔서 고맙습니다. 👍
