### ISSUE TITLE
[Deprecated] `from django.conf.urls import url`

### ISSUE THREAD

**Issue by aciddust** [raccoonyy/django-sample-for-docker-compose#4]
```python
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]
```
was deprecated in 3.0 and removed in the latest release of Django 4.0.  

need to specify Django version information in `requirements.txt` or edit `djangosample/urls.py` like this..

```python
from django.urls import re_path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
]
```

May I proceed PR about this issue?

---  

Ref
> https://docs.djangoproject.com/en/4.0/ref/urls/#re-path

**Comment by raccoonyy** [comment]
Sure thing. Thank you!
(I think it's better to specify Django version to 4.x)
